---

# pre-condition
- name: stop tomcat
  action: service name=tomcat8 state=stopped
  become: true
  when: ansible_connection != 'docker'

- name: make sure web archive upload folder exists
  action: file path="{{ webapps_archive_folder }}" state=directory mode=0755 owner={{ tomcat_user }} group={{ tomcat_group }}
  become: true

- name: file informations last success full application
  action: stat path="{{ tomcat_doc_base }}/current"
  register: locationLastApplication

# deployment
- block:

  - include: deployment.yml

  rescue:

    - include: rollback_previous_version.yml

  always:

    - include: always.yml
